name: Build dev Docker image
on:
  push:
    paths:
      - '.gitpod.Dockerfile'
    branches:
      - main
      
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@1

      - name: Log in to the Container registry
        uses: docker/login-action@1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3
        with:
          images: ghcr.io/tomglennhs/gitpod

      - name: Build and push Docker image
        uses: docker/build-push-action@2
        with:
          context: .
          file: .gitpod.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
